name: Package Devcontainers Reusable

on:
  repository_dispatch:
    types:
      - build-humble
      - build-jazzy
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  package-devcontainers:
    strategy:
      fail-fast: false
      matrix:
        os: [humble, jazzy]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and run Dev Container task
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/isri-aist/azure-kinect-container
          imageTag: ${{ matrix.os }}
          configFile: ./../devcontainer/${{ matrix.os }}/devcontainer.json
          push: always
          runCmd: make ci-build
